### ISSUE TITLE
B 站无法播放

### ISSUE THREAD

**Issue by Heporis** [qianjiachun/uni-live#5]
浏览器插件的同屏播放倒是可以播放B站的。
live.douyuex.com和浏览器插件的同屏播放有一个问题，×掉后，网络连接不会断开，会一直占用网络，直到刷新或关闭当前网页。

**Comment by Heporis** [comment]
赶快修复啊，我要看Ti11的比赛🤣

**Comment by qianjiachun** [comment]
已知，会尽快修复
另外注意一下言辞，不要催我，我是无偿加班做这些，我也很累，并没有义务“赶快”修复
如果觉得很急你可以参与到开源而不是催着作者更新

**Comment by Heporis** [comment]
> 已知，会尽快修复 另外注意一下言辞，不要催我，我是无偿加班做这些，我也很累，并没有义务“赶快”修复 如果觉得很急你可以参与到开源而不是催着作者更新

😅好的，谢谢你！我先用直链看

**Comment by qianjiachun** [comment]
已修复b站解析。
无法停止拉流的BUG还在研究中，等待后续更新

**Comment by qianjiachun** [comment]
douyuex插件无法断流的bug已经修复。
联播无法断流的bug待解决中，如果修复了会在这个issue里提醒。
